spring:
  application:
    name: service-discovery
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 10113

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
