spring:
  jpa:
     hibernate:
       ddl-auto: none
  datasource:
     driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/MyDB
    #username: BabySama
    # password: BabySama
    url: jdbc:postgresql://42.96.44.215:5432/hisdb
    username: his
    password: 123456@
  zipkin:
    base-url: http://localhost:9411/

server:
   port: 10114

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh
eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     serviceUrl:
       defaultZone: http://localhost:10113/eureka
       
logging:
  level:
    root: INFO
  file: administration.log